### ISSUE TITLE
关于版权的问题

### ISSUE THREAD

**Issue by amehito** [crmeb/crmeb_java#6]
1.请问我可以直接将代码下载、部署安装给客户，不支付贵公司任何费用吗？
2.假如1成立，那么贵公司官网售卖的crmeb_java源码与本源码不同是吗？

**Comment by sugar1569** [comment]
保留版权可以给客户用，商业版功能有区别的，主要提供更多服务，支持更新包升级的发自PORSCHE DESIGN HUAWEI Mate 40 RS-------- 原始邮件 --------发件人： amehito ***@***.***>日期： 2021年3月15日周一 晚上10:07收件人： crmeb/crmeb_java ***@***.***>抄送： Subscribed ***@***.***>主    题： [crmeb/crmeb_java] 关于版权的问题 (#6)

1.请问我可以直接将代码下载、部署安装给客户，不支付贵公司任何费用吗？

2.假如1成立，那么贵公司官网售卖的crmeb_java源码与本源码不同是吗？

**Comment by xbdazz** [comment]
保留版权可以给客户用，商业版功能有区别的，主要提供更多服务，支持更新包升级
