### ISSUE TITLE
Java端启动报异常，连不上数据库

### ISSUE THREAD

**Issue by chimei955** [crmeb/crmeb_java#7]
java.sql.SQLException: url not set
[com.alibaba.druid.pool.DruidDataSource:978] : {dataSource-1} init error

请问这个问题如何解？连不上数据库

**Comment by sugar1569** [comment]
群里咨询技术吧，开源说明里面有群的发自PORSCHE DESIGN HUAWEI Mate 40 RS-------- 原始邮件 --------发件人： chimei955 ***@***.***>日期： 2021年4月13日周二 晚上7:24收件人： crmeb/crmeb_java ***@***.***>抄送： Subscribed ***@***.***>主    题： [crmeb/crmeb_java] Java端启动报异常，连不上数据库 (#7)

java.sql.SQLException: url not set

[com.alibaba.druid.pool.DruidDataSource:978] : {dataSource-1} init error

请问这个问题如何解？连不上数据库

**Comment by xbdazz** [comment]
yml 配置不正确 查看格式是不是yml 层级乱了
